name: Lập trình cuộc sống
description: Chỉ là blog của một thằng coder
home_description: 
avatar: images/logo.gif
baseurl: 
site_url: "http://laptrinhcuocsong.com"
default_post_avatar: images/logo.gif
permalink: /:title.html
version: v1.2.0
markdown: kramdown
syntax_highlighter: rouge
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
defaults:
  values:
    layout: "post"
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
# paginate
paginate: 10
